version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database_one
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  fluentbit:
    image: fluent/fluent-bit:latest
    volumes:
    - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    - ./logs:/app/logs
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf


  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/database_one?schema=public
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
